INTERNAL_GPU: include trace_gpu.h when CONFIG_HFI1_AMD=y is set
Building with CONFIG_HFI1_AMD=y, CONFIG_HFI1_NVIDIA=n or unset fails
like this:

    drivers/infiniband/hw/hfi1/tid_amd.c: In function ‘amd_pin_pages’:
    drivers/infiniband/hw/hfi1/tid_amd.c:593:9: error: implicit declaration of function ‘trace_pin_rcv_pages_gpu’ [-Werror=implicit-function-declaration]
      593 |         trace_pin_rcv_pages_gpu(HFI1_MEMINFO_TYPE_AMD, tbuf->vaddr, abuf->pages->va,
          |         ^~~~~~~~~~~~~~~~~~~~~~~
      CC [M]  drivers/net/ethernet/mellanox/mlx5/core/en/xsk/setup.o
      LD [M]  drivers/infiniband/core/rdma_cm.o
    drivers/infiniband/hw/hfi1/tid_amd.c:602:9: error: implicit declaration of function ‘trace_recv_pin_gpu_pages_fail’ [-Werror=implicit-function-declaration]
      602 |         trace_recv_pin_gpu_pages_fail(HFI1_MEMINFO_TYPE_AMD, ret, tbuf->vaddr, tbuf->length);
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      CC [M]  drivers/net/ethernet/mellanox/mlx5/core/en/xsk/rx.o
      CC [M]  drivers/net/ethernet/mellanox/mlx5/core/en/xsk/tx.o
      LD [M]  drivers/infiniband/core/ib_umad.o
    cc1: all warnings being treated as errors
      CC [M]  drivers/net/ethernet/mellanox/mlx5/core/en/devlink.o
    make[6]: *** [scripts/Makefile.build:243: drivers/infiniband/hw/hfi1/tid_amd.o] Error 1
    make[6]: *** Waiting for unfinished jobs....

Fix this by including hfi1/trace_gpu.h in hfi1/trace.h when
CONFIG_HFI1_AMD is defined.

INTERNAL: STL-70096 hfi1-AMD build fails if CONFIG_HFI1_NVIDIA=y not set

Fixes: 583ce9d75905 ("INTERNAL_GPU: add trace_gpu tracepoints to tid_amd")
Signed-off-by: Brendan Cunningham <bcunningham@cornelisnetworks.com>
(cherry picked from commit 8162f56b788a71c47962183c047bc95353ce2e33)