INTERNAL_GPU: fix min() "lacks a cast" error in TID-AMD DMA iterator code
INTERNAL: This commit is only needed when building hfi1 with
INTERNAL: CONFIG_HFI1_AMD=y against include/linux/minmax.h missing
INTERNAL: certain fixes that are upstream as early as v6.7.

hfi1 'CONFIG_HFI1_AMD=y' build fails with this error:

    In file included from ./include/linux/kernel.h:27,
                     from ./arch/x86/include/asm/percpu.h:27,
                     from ./arch/x86/include/asm/preempt.h:6,
                     from ./include/linux/preempt.h:79,
                     from ./include/linux/spinlock.h:56,
                     from ./include/linux/kref.h:16,
                     from drivers/infiniband/hw/hfi1/tid_amd.c:12:
    drivers/infiniband/hw/hfi1/tid_amd.c: In function ‘__amd_page_iter_dma_len’:
    ./include/linux/minmax.h:20:35: error: comparison of distinct pointer types lacks a cast [-Werror]
       20 |         (!!(sizeof((typeof(x) *)1 == (typeof(y) *)1)))
          |                                   ^~
    ./include/linux/minmax.h:26:18: note: in expansion of macro ‘__typecheck’
       26 |                 (__typecheck(x, y) && __no_side_effects(x, y))
          |                  ^~~~~~~~~~~
    ./include/linux/minmax.h:36:31: note: in expansion of macro ‘__safe_cmp’
       36 |         __builtin_choose_expr(__safe_cmp(x, y), \
          |                               ^~~~~~~~~~
    ./include/linux/minmax.h:67:25: note: in expansion of macro ‘__careful_cmp’
       67 | #define min(x, y)       __careful_cmp(x, y, <)
          |                         ^~~~~~~~~~~~~
    drivers/infiniband/hw/hfi1/tid_amd.c:122:15: note: in expansion of macro ‘min’
      122 |         len = min(len - iter->offset, MAX_EXPECTED_BUFFER);
          |               ^~~
    cc1: all warnings being treated as errors
    make[6]: *** [scripts/Makefile.build:243: drivers/infiniband/hw/hfi1/tid_amd.o] Error 1
    make[6]: *** Waiting for unfinished jobs....
    make[5]: *** [scripts/Makefile.build:477: drivers/infiniband/hw/hfi1] Error 2
    make[4]: *** [scripts/Makefile.build:477: drivers/infiniband/hw] Error 2
    make[3]: *** [scripts/Makefile.build:477: drivers/infiniband] Error 2
    make[3]: *** Waiting for unfinished jobs....
    make[2]: *** [scripts/Makefile.build:477: drivers] Error 2
    make[1]: *** [/local_home/bcunningham/projects/wld-amd-cache-fix/Makefile:2020: .] Error 2
    make: *** [Makefile:234: __sub-make] Error 2

Changing 'min(...)' to 'min_t(size_t,...)' fixes the error.

INTERNAL: STL-70095 tid_amd.c "error: comparison of distinct pointer types lacks a cast [-Werror]"

Signed-off-by: Brendan Cunningham <bcunningham@cornelisnetworks.com>
(cherry picked from commit 0d3b541783c1b7b4414f3961c96e8620fbeaf32b)