BUILD: Fix hfi1-AMD linking errors
Missing code in build scripts and Makefile resulted in compile and
linking errors like these when building with AMD GPU support:

    ./build_it_test_it.sh amd notest
    ...
      CC [M]  /tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/hfi1/pin_amd.o
      LD [M]  /tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/hfi1/hfi1.o
      MODPOST /tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/Module.symvers
    ERROR: modpost: "hfi1_tid_amd_free" [/tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/hfi1/hfi1.ko] undefined!
    ERROR: modpost: "amdkfd_query_rdma_interface" [/tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/hfi1/hfi1.ko] undefined!
    ERROR: modpost: "hfi1_tid_amd_init" [/tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/hfi1/hfi1.ko] undefined!
    make[2]: *** [scripts/Makefile.modpost:128: /tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/Module.symvers] Error 1
    make[1]: *** [Makefile:1858: modules] Error 2

Signed-off-by: Brendan Cunningham <bcunningham@cornelisnetworks.com>
Signed-off-by: Dennis Dalessandro <dennis.dalessandro@cornelisnetworks.com>