BUILD: Fix hfi1-NVIDIA build errors
Missing Makefile code caused compile and linking errors like these:

    $ ./build_it_test_it.sh nvidia notest
    ...
      CC [M]  /tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/hfi1/pin_nvidia.o
      LD [M]  /tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/hfi1/hfi1.o
      MODPOST /tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/Module.symvers
    ERROR: modpost: "hfi1_tid_nvidia_init" [/tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/hfi1/hfi1.ko] undefined!
    ERROR: modpost: "hfi1_gdr_device_create" [/tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/hfi1/hfi1.ko] undefined!
    ERROR: modpost: "hfi1_gdr_device_remove" [/tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/hfi1/hfi1.ko] undefined!
    ERROR: modpost: "hfi1_tid_nvidia_free" [/tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/hfi1/hfi1.ko] undefined!
    make[2]: *** [scripts/Makefile.modpost:128: /tmp/tmpbuild/rpmbuild/BUILD/opxs-kernel-updates-5.14.0_503.14.1.el9_5.x86_64/Module.symvers] Error 1
    make[1]: *** [Makefile:1858: modules] Error 2
    make[1]: Leaving directory '/usr/src/kernels/5.14.0-503.14.1.el9_5.x86_64'
    make: *** [Makefile:21: default] Error 2
    error: Bad exit status from /var/tmp/rpm-tmp.PaxkMU (%build)

    RPM build errors:
        Bad exit status from /var/tmp/rpm-tmp.PaxkMU (%build)
    Build failed!

Adding the missing code fixes the issue.

Signed-off-by: Brendan Cunningham <bcunningham@cornelisnetworks.com>
Signed-off-by: Dennis Dalessandro <dennis.dalessandro@cornelisnetworks.com>