INTERNAL_GPU: Fix missing includes with kmod-nvidia-open-dkms
hfi1 with 'CONFIG_HFI1_NVIDIA=y' fails to build with
kmod-nvidia-open-dkms because of an include path change between
kmod-nvidia-open-dkms and the old kmod-nvidia-dkms:

In file included from drivers/infiniband/hw/hfi1/trace_nvidia.h:14,
	  from drivers/infiniband/hw/hfi1/trace.h:27,
	  from drivers/infiniband/hw/hfi1/affinity.c:14:
drivers/infiniband/hw/hfi1/pin_nvidia.h:12:10: fatal error: nvidia/nv-p2p.h: No such file or directory
12 | #include <nvidia/nv-p2p.h>
|          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[6]: *** [scripts/Makefile.build:243: drivers/infiniband/hw/hfi1/affinity.o] Error 1
make[6]: *** Waiting for unfinished jobs....

Change hfi1/Makefile to find the correct include path for both
kmod-nvidia-open-dkms and kmod-nvidia-dkms.

INTERNAL: STL-70083 hfi1-NVIDIA build error with nvidia-open driver

Signed-off-by: Brendan Cunningham <bcunningham@cornelisnetworks.com>
(cherry picked from commit adda8c59ec9a899916b14e8d652b195d877d8b8e)